Updated vault check script + roles

diff --git a/ionos/wallet/vault/templates/cronjob.yaml b/ionos/wallet/vault/templates/cronjob.yaml
--- a/ionos/wallet/vault/templates/cronjob.yaml
+++ b/ionos/wallet/vault/templates/cronjob.yaml
@@ -18,107 +18,133 @@ spec:
               command: ["/bin/sh", "-c"]
               args:
                 - |
-                  #!/bin/sh
+                    #!/bin/sh
 
-                  NAMESPACE="in2"
+                    NAMESPACE="in2"
 
-                  echo "Initializing check..."
+                    echo "Initializing check..."
 
-                  # Get the Vault pod name
-                  VAULT_POD_NAME=$(kubectl get pods -n "$NAMESPACE" -l app.kubernetes.io/instance=vault -o jsonpath='{.items[0].metadata.name}')
+                    # Get the Vault pod name
+                    VAULT_POD_NAME="{{ .Values.vaultPodName }}"
 
-                  # Check if VAULT_POD_NAME was obtained correctly
-                  if [ -z "$VAULT_POD_NAME" ]; then
-                    echo "Error: Could not retrieve the Vault pod name."
-                    exit 1
-                  fi
+                    echo "Vault pod name: $VAULT_POD_NAME"
 
-                  echo "Vault pod name: $VAULT_POD_NAME"
-
-                  # Check Vault status
-                  STATUS=$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault status 2>&1")
-                  if [ -z "$STATUS" ]; then
-                    echo "Error: Failed to get Vault status. That means the Vault is not initialized"
-                    INITIALIZED="false"
-                    SEALED="true"
-                  fi
-
-                  echo "Status: $STATUS"
-
-                  # Extract Vault initialization and seal status
-                  INITIALIZED=$(echo "$STATUS" | grep 'Initialized' | awk '{print $2}')
-                  SEALED=$(echo "$STATUS" | grep 'Sealed' | awk '{print $2}')
-
-                  # Check if the variables were correctly assigned
-                  if [ -z "$INITIALIZED" ] || [ -z "$SEALED" ]; then
-                    echo "Error: Could not determine Vault status from the output."
-                    exit 1
-                  fi
-
-                  echo "Vault status: Initialized=$INITIALIZED, Sealed=$SEALED"
-
-                  if [ "$INITIALIZED" = "false" ] && [ "$SEALED" = "true" ]; then
-                    echo "Vault is not initialized and is sealed. Proceeding to initialize Vault..."
-
-                    # Initialize Vault
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'vault operator init -format=json > /dev/shm/vault_init.json'
-                    if [ -z "$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'cat /dev/shm/vault_init.json')" ]; then
-                      echo "Error: Failed to initialize Vault."
-                      exit 1
+                    # Check Vault status
+                    STATUS=$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault status 2>&1")
+                    if [ -z "$STATUS" ]; then
+                      echo "No Vault status. That means the Vault is not initialized"
+                      INITIALIZED="false"
+                      SEALED="true"
                     fi
-                    
-                    # Extract unseal keys and root token from the JSON file using awk
-                    UNSEAL_KEYS=$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'awk '\''/"unseal_keys_b64": \[/{flag=1; next} /],/{flag=0} flag'\'' /dev/shm/vault_init.json')
-                    ROOT_TOKEN=$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'awk -F\" "/root_token/{print \$4}" /dev/shm/vault_init.json')
 
-                    if [ -z "$UNSEAL_KEYS" ] && [ -z "$ROOT_TOKEN" ]; then
-                      echo "Error: Failed to retrieve unseal keys or root token."
+                    # Function to check unseal status
+                    check_unseal_status() {
+                      kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault status" | grep 'Sealed' | awk '{print $2}'
+                    }
+
+                    echo "Status: $STATUS"
+
+                    # Extract Vault initialization and seal status
+                    INITIALIZED=$(echo "$STATUS" | grep 'Initialized' | awk '{print $2}')
+                    SEALED=$(echo "$STATUS" | grep 'Sealed' | awk '{print $2}')
+
+                    # Check if the variables were correctly assigned
+                    if [ -z "$INITIALIZED" ] || [ -z "$SEALED" ]; then
+                      echo "Error: Could not determine Vault status from the output."
                       exit 1
                     fi
 
-                    # Decode the unseal keys
-                    UNSEAL_KEY_1=$(echo "$UNSEAL_KEYS" | head -n 1 | tr -d '", ')
-                    UNSEAL_KEY_2=$(echo "$UNSEAL_KEYS" | sed -n '2p' | tr -d '", ')
-                    UNSEAL_KEY_3=$(echo "$UNSEAL_KEYS" | sed -n '3p' | tr -d '", ')
+                    echo "Vault status: Initialized=$INITIALIZED, Sealed=$SEALED"
 
-                    # Delete the old Kubernetes Secret, if it exists
-                    kubectl delete secret vault-unseal-keys -n "$NAMESPACE" --ignore-not-found
+                    if [ "$INITIALIZED" = "false" ] && [ "$SEALED" = "true" ]; then
+                      echo "Vault is not initialized and is sealed. Proceeding to initialize Vault..."
 
-                    # Create a new Kubernetes Secret with the unseal keys
-                    kubectl create secret generic vault-unseal-keys \
-                      --from-literal=unseal_key_1="$UNSEAL_KEY_1" \
-                      --from-literal=unseal_key_2="$UNSEAL_KEY_2" \
-                      --from-literal=unseal_key_3="$UNSEAL_KEY_3" \
-                      --namespace "$NAMESPACE"
+                      # Initialize Vault
+                      kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'vault operator init -format=json > /dev/shm/vault_init.json'
+                      if [ -z "$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'cat /dev/shm/vault_init.json')" ]; then
+                        echo "Error: Failed to initialize Vault."
+                        exit 1
+                      fi
+                      
+                      # Extract unseal keys and root token from the JSON file using awk
+                      UNSEAL_KEYS=$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'awk '\''/"unseal_keys_b64": \[/{flag=1; next} /],/{flag=0} flag'\'' /dev/shm/vault_init.json')
+                      ROOT_TOKEN=$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'awk -F\" "/root_token/{print \$4}" /dev/shm/vault_init.json')
 
-                    # Extract unseal keys from Kubernetes Secrets
-                    UNSEAL_KEY_1=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_1}' | base64 --decode)
-                    UNSEAL_KEY_2=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_2}' | base64 --decode)
-                    UNSEAL_KEY_3=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_3}' | base64 --decode)
+                      if [ -z "$UNSEAL_KEYS" ] && [ -z "$ROOT_TOKEN" ]; then
+                        echo "Error: Failed to retrieve unseal keys or root token."
+                        exit 1
+                      fi
 
-                    # Unseal Vault using the unseal keys inside the Vault pod
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_1"
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_2"
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_3"
+                      # Decode the unseal keys
+                      UNSEAL_KEY_1=$(echo "$UNSEAL_KEYS" | head -n 1 | tr -d '", ')
+                      UNSEAL_KEY_2=$(echo "$UNSEAL_KEYS" | sed -n '2p' | tr -d '", ')
+                      UNSEAL_KEY_3=$(echo "$UNSEAL_KEYS" | sed -n '3p' | tr -d '", ')
+                      UNSEAL_KEY_4=$(echo "$UNSEAL_KEYS" | sed -n '4p' | tr -d '", ')
+                      UNSEAL_KEY_5=$(echo "$UNSEAL_KEYS" | tail -n 1 | tr -d '", ')
 
-                    echo "Vault initialized and unseal keys stored in Kubernetes Secret."
+                      # Create a new Kubernetes Secret with the unseal keys
+                      kubectl create secret generic vault-unseal-keys \
+                        --from-literal=unseal_key_1="$UNSEAL_KEY_1" \
+                        --from-literal=unseal_key_2="$UNSEAL_KEY_2" \
+                        --from-literal=unseal_key_3="$UNSEAL_KEY_3" \
+                        --from-literal=unseal_key_4="$UNSEAL_KEY_4" \
+                        --from-literal=unseal_key_5="$UNSEAL_KEY_5" \
+                        --from-literal=root="$ROOT_TOKEN" \
+                        --namespace "$NAMESPACE"
 
-                  elif [ "$INITIALIZED" = "true" ] && [ "$SEALED" = "true" ]; then
-                    echo "Vault is initialized and sealed. Proceeding to unseal Vault..."
+                      # Extract unseal keys from Kubernetes Secrets
+                      UNSEAL_KEY_1=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_1}' | base64 --decode)
+                      UNSEAL_KEY_2=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_2}' | base64 --decode)
+                      UNSEAL_KEY_3=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_3}' | base64 --decode)
+                      UNSEAL_KEY_4=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_4}' | base64 --decode)
+                      UNSEAL_KEY_5=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_5}' | base64 --decode)
+                      
+                      # Try to unseal with each key until the Vault is unsealed
+                      for key in "$UNSEAL_KEY_1" "$UNSEAL_KEY_2" "$UNSEAL_KEY_3" "$UNSEAL_KEY_4" "$UNSEAL_KEY_5"; do
+                        kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $key"
+                        sealed_status=$(check_unseal_status)
+                        echo "Sealed status: $sealed_status"
+                        if [ "$sealed_status" = "false" ]; then
+                          echo "Vault successfully unsealed."
+                          break
+                        fi
+                      done
 
-                    # Extract unseal keys from Kubernetes Secrets
-                    UNSEAL_KEY_1=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_1}' | base64 --decode)
-                    UNSEAL_KEY_2=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_2}' | base64 --decode)
-                    UNSEAL_KEY_3=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_3}' | base64 --decode)
+                      # Verify if the Vault is still sealed after trying all keys
+                      if [ "$sealed_status" = "true" ]; then
+                        echo "Failed to unseal the Vault with the provided keys."
+                      fi
 
-                    echo "Unsealing Vault with keys: $UNSEAL_KEY_1, $UNSEAL_KEY_2, $UNSEAL_KEY_3"
+                      echo "Vault initialized and unseal keys stored in Kubernetes Secret."
 
-                    # Unseal Vault using the unseal keys inside the Vault pod
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_1"
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_2"
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_3"
+                    elif [ "$INITIALIZED" = "true" ] && [ "$SEALED" = "true" ]; then
+                      echo "Vault is initialized and sealed. Proceeding to unseal Vault..."
 
-                  else
-                    echo "Vault is already unsealed or the status is unknown."
-                  fi
+                      # Extract unseal keys from Kubernetes Secrets
+                      UNSEAL_KEY_1=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_1}' | base64 --decode)
+                      UNSEAL_KEY_2=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_2}' | base64 --decode)
+                      UNSEAL_KEY_3=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_3}' | base64 --decode)
+                      UNSEAL_KEY_4=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_4}' | base64 --decode)
+                      UNSEAL_KEY_5=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_5}' | base64 --decode)
+
+                      UNSEAL_KEYS=("$UNSEAL_KEY_1" "$UNSEAL_KEY_2" "$UNSEAL_KEY_3" "$UNSEAL_KEY_4" "$UNSEAL_KEY_5")
+
+                      # Try to unseal with each key until the Vault is unsealed
+                      for key in "${UNSEAL_KEYS[@]}"; do
+                        kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $key"
+                        sealed_status=$(check_unseal_status)
+                        echo "Sealed status: $sealed_status"
+                        if [ "$sealed_status" = "false" ]; then
+                          echo "Vault successfully unsealed."
+                          break
+                        fi
+                      done
+
+                      if [ "$sealed_status" = "true" ]; then
+                        echo "Failed to unseal the Vault with the provided keys."
+                      fi
+
+                    else
+                      echo "Vault is already unsealed or the status is unknown."
+                    fi
           restartPolicy: OnFailure
