Added ttl to cronjob

diff --git a/ionos/wallet/vault/templates/cronjob.yaml b/ionos/wallet/vault/templates/cronjob.yaml
--- a/ionos/wallet/vault/templates/cronjob.yaml
+++ b/ionos/wallet/vault/templates/cronjob.yaml
@@ -8,6 +8,7 @@ spec:
   schedule: "*/5 * * * *"  # Run every 5 minutes
   jobTemplate:
     spec:
+      ttlSecondsAfterFinished: 0  # Delete job immediately after completion
       template:
         spec:
           serviceAccountName: vault-check-sa
@@ -20,12 +21,13 @@ spec:
                   #!/bin/sh
 
                   NAMESPACE="in2"
+
                   echo "Initializing check..."
 
-                  # Retrieve the Vault pod name
+                  # Get the Vault pod name
                   VAULT_POD_NAME=$(kubectl get pods -n "$NAMESPACE" -l app.kubernetes.io/instance=vault -o jsonpath='{.items[0].metadata.name}')
 
-                  # Check if the pod name was retrieved correctly
+                  # Check if VAULT_POD_NAME was obtained correctly
                   if [ -z "$VAULT_POD_NAME" ]; then
                     echo "Error: Could not retrieve the Vault pod name."
                     exit 1
@@ -33,22 +35,20 @@ spec:
 
                   echo "Vault pod name: $VAULT_POD_NAME"
 
-                  # Check the Vault status
+                  # Check Vault status
                   STATUS=$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault status 2>&1")
-
                   if [ $? -ne 0 ]; then
-                    echo "Error: Failed to get Vault status. It means that the Vault is not initialized."
-                    $INITIALIZED = "false"
-                    $SEALED = "true"
+                    echo "Error: Failed to get Vault status."
+                    exit 1
                   fi
 
                   echo "Status: $STATUS"
 
-                  # Assign status variables
+                  # Extract Vault initialization and seal status
                   INITIALIZED=$(echo "$STATUS" | grep 'Initialized' | awk '{print $2}')
                   SEALED=$(echo "$STATUS" | grep 'Sealed' | awk '{print $2}')
 
-                  # Check if the status variables were assigned correctly
+                  # Check if the variables were correctly assigned
                   if [ -z "$INITIALIZED" ] || [ -z "$SEALED" ]; then
                     echo "Error: Could not determine Vault status from the output."
                     exit 1
@@ -56,19 +56,17 @@ spec:
 
                   echo "Vault status: Initialized=$INITIALIZED, Sealed=$SEALED"
 
-                  # If Vault is not initialized and is sealed, initialize Vault
                   if [ "$INITIALIZED" = "false" ] && [ "$SEALED" = "true" ]; then
                     echo "Vault is not initialized and is sealed. Proceeding to initialize Vault..."
 
-                    # Initialize Vault inside the Vault pod
+                    # Initialize Vault
                     kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'vault operator init -format=json > /dev/shm/vault_init.json'
-                    
                     if [ $? -ne 0 ]; then
                       echo "Error: Failed to initialize Vault."
                       exit 1
                     fi
 
-                    # Extract the unseal keys and root token from the JSON file
+                    # Extract unseal keys and root token from the JSON file using grep and cut
                     UNSEAL_KEYS=$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'cat /dev/shm/vault_init.json | grep -oP "(?<=unseal_keys_b64\": \[)[^]]+"')
                     ROOT_TOKEN=$(kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c 'cat /dev/shm/vault_init.json | grep -oP "(?<=root_token\": \")[^\"]+"')
 
@@ -82,13 +80,10 @@ spec:
                     UNSEAL_KEY_2=$(echo "$UNSEAL_KEYS" | cut -d',' -f2 | tr -d '"')
                     UNSEAL_KEY_3=$(echo "$UNSEAL_KEYS" | cut -d',' -f3 | tr -d '"')
 
-                    # Unseal Vault using the unseal keys inside the Vault pod
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_1"
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_2"
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_3"
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault secrets enable -version=1 kv"
+                    # Delete the old Kubernetes Secret, if it exists
+                    kubectl delete secret vault-unseal-keys -n "$NAMESPACE" --ignore-not-found
 
-                    # Store unseal keys in a Kubernetes Secret
+                    # Create a new Kubernetes Secret with the unseal keys
                     kubectl create secret generic vault-unseal-keys \
                       --from-literal=unseal_key_1="$UNSEAL_KEY_1" \
                       --from-literal=unseal_key_2="$UNSEAL_KEY_2" \
@@ -97,11 +92,10 @@ spec:
 
                     echo "Vault initialized and unseal keys stored in Kubernetes Secret."
 
-                  # If Vault is initialized but sealed, unseal Vault
                   elif [ "$INITIALIZED" = "true" ] && [ "$SEALED" = "true" ]; then
                     echo "Vault is initialized and sealed. Proceeding to unseal Vault..."
 
-                    # Retrieve unseal keys from Kubernetes Secrets
+                    # Extract unseal keys from Kubernetes Secrets
                     UNSEAL_KEY_1=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_1}' | base64 --decode)
                     UNSEAL_KEY_2=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_2}' | base64 --decode)
                     UNSEAL_KEY_3=$(kubectl get secret vault-unseal-keys -n "$NAMESPACE" -o jsonpath='{.data.unseal_key_3}' | base64 --decode)
@@ -112,9 +106,6 @@ spec:
                     kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_1"
                     kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_2"
                     kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault operator unseal $UNSEAL_KEY_3"
-                    kubectl exec -n "$NAMESPACE" "$VAULT_POD_NAME" -- /bin/sh -c "vault secrets enable -version=1 kv"
-
-                    echo "Vault unsealed and secrets enabled."
 
                   else
                     echo "Vault is already unsealed or the status is unknown."
